In [2]:
import cv2
import numpy as np
import sklearn.cluster
import pickle
class camera_Data:
    def __init__(self, name, cam_R, cam_T, flag):
        self.name = name
        self.R = cam_R
        self.T = cam_T
        self.flag = flag

        
def cluster_pose(cam_R, cam_T):
    """
    :type ls_T: list[Transform]
    """
    # cluster t
    print(len(cam_T))
    meanshift_t = sklearn.cluster.MeanShift(bandwidth=1000, bin_seeding=True)
    meanshift_t.fit(cam_T)
    print(meanshift_t.labels_)
    #assert np.count_nonzero(meanshift_t.labels_ == 0) > (0.7 * len(cam_T))
    t = meanshift_t.cluster_centers_[0]
    print(t)

    # cluster R
    _Rs = np.array(cam_R)[meanshift_t.labels_ == 0]
    _Rs = _Rs.reshape((-1, 9))
    meanshift_R = sklearn.cluster.MeanShift(bandwidth=0.1)
    meanshift_R.fit(_Rs)
    print(meanshift_R.labels_)
    _tmp = meanshift_t.labels_ == 0
    assert isinstance(_tmp, np.ndarray)
    assert np.count_nonzero(_tmp) > (0.7 * len(_Rs))
    R = meanshift_R.cluster_centers_[0].reshape((3, 3))

    # normalize
    R = cv2.Rodrigues(cv2.Rodrigues(R)[0])[0]
    return R, t

def RT_calculate(cam1, cam2):
    f = cam1.flag & cam2.flag
    r1 = cam1.R[f]
    t1 = cam1.T[f]
    r2 = cam2.R[f]
    t2 = cam2.T[f]
    R = []
    T = []
    for i in range(r1.shape[0]):
        r12 = np.dot(cv2.Rodrigues(r1[i])[0], cv2.Rodrigues(r2[i])[0].T)
        t12 = t1[i] - np.dot(r12, t2[i])
        R.append(r12)
        T.append(t12)
    R = np.squeeze(np.asarray(R))
    T = np.squeeze(np.asarray(T))
    
    return cluster_pose(R, T)
    

In [ ]:
dir = r"C:\Users\lovettxh\Documents\GitHub\multi_camera_calibration\calibration\1024"
cam_list = ['kinect_v2_1', 'azure_kinect_1','azure_kinect_0',  'azure_kinect_2', 'kinect_v2_2']
start_idx = [0, 0, 0, 0, 0]
n_list = [124, 124, 124, 124, 124]
col = 8
row = 11
square_size = 60.
objp = np.zeros((col*row, 3), np.float32)
objp[:, :2] = np.mgrid[0:col, 0:row].T.reshape(-1, 2) * square_size
h = 0
w = 0
corner_m = []
obj_m = []
cams = {}
for idx, cam in enumerate(cam_list):
    obj_points = []
    img_points = []
    cam_R, cam_T, flag = [], [], []
    cam_dir = "%s/%s_calib_snap" % (dir, cam)
    for i in range(n_list[idx]):
        filename = '%s/color%04i.jpg' % (cam_dir, i + start_idx[idx])
        print(i)
        img = cv2.imread(filename)
        h, w = img.shape[0], img.shape[1]
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        ret, corners = cv2.findChessboardCorners(gray, (col, row), None)
        flag.append(ret)
        if ret:
            print(filename)
            corners2 = cv2.cornerSubPix(gray, corners, (5, 5), (-1, -1), None)
            obj_points.append(objp)
            img_points.append(np.squeeze(corners2))
        else:
            obj_points.append(objp)
            img_points.append(np.zeros((col*row, 2)))    
    
    obj_points= np.array(obj_points).astype('float32')
    img_points= np.array(img_points).astype('float32')
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points[flag], img_points[flag], (w, h), None, None, flags=cv2.CALIB_RATIONAL_MODEL)
    for i in range(n_list[idx]):
        if flag[i]:
            retval, rvec, tvec = cv2.solvePnP(objectPoints=obj_points[i], imagePoints=img_points[i], cameraMatrix=mtx, distCoeffs=dist)
            cam_R.append(rvec)
            cam_T.append(tvec)
        else:
            cam_R.append(np.zeros((3,1)))
            cam_T.append(np.zeros((3,1)))
    cams[cam] = camera_Data(cam, np.asarray(cam_R), np.asarray(cam_T), np.asarray(flag))

In [22]:
result = {}
temp_r , temp_t = RT_calculate(cams[cam_list[3]], cams[cam_list[4]])
result[cam_list[3] + "-" + cam_list[4] + "_R"] = temp_r
result[cam_list[3] + "-" + cam_list[4] + "_T"] = temp_t
temp_r , temp_t = RT_calculate(cams[cam_list[2]], cams[cam_list[3]])
result[cam_list[2] + "-" + cam_list[3] + "_R"] = temp_r
result[cam_list[2] + "-" + cam_list[3] + "_T"] = temp_t
temp_r , temp_t = RT_calculate(cams[cam_list[2]], cams[cam_list[1]])
result[cam_list[2] + "-" + cam_list[1] + "_R"] = temp_r
result[cam_list[2] + "-" + cam_list[1] + "_T"] = temp_t
temp_r , temp_t = RT_calculate(cams[cam_list[1]], cams[cam_list[0]])
result[cam_list[1] + "-" + cam_list[0] + "_R"] = temp_r
result[cam_list[1] + "-" + cam_list[0] + "_T"] = temp_t
print(result)
with open('extrinsic.pkl','wb') as handle:
    pickle.dump(result, handle)

18
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1755.05411089 -433.15100508 1156.9553154 ]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
42
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
[1522.4574341   114.79700697  976.86899334]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]
39
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]
[-1668.51543707   147.87110352   802.06265815]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]
18
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[-1937.00554847  -244.77167949  1052.98422726]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
{'azure_kinect_2-kinect_v2_2_R': array([[ 0.47807969,  0.18101   , -0.85946215],
       [-0.1261027 ,  0.9825414 ,  0.13678633],
       [ 0.86921684,  0.04298573,  0.49255894]]), 'azure_kinect_2-kinect_v2_2_T': array([1755.05411089, -433.15100508, 1156.9553154 ]), 'azure_kinect_0-azure_kinect_2_R': array([[ 0.5854904

In [4]:
result = {}
cam_list = ['kinect_v2_1', 'azure_kinect_1','azure_kinect_0',  'azure_kinect_2', 'kinect_v2_2']
result[cam_list[3] + "-" + cam_list[4] + "_R"] = np.array([[ 0.37361034,  0.18518875, -0.90891168],
       [-0.17581992,  0.97624312,  0.12663618],
       [ 0.91077037,  0.11249219,  0.39729439]])
result[cam_list[3] + "-" + cam_list[4] + "_T"] = np.array([1960.23753113, -579.31185515, 1098.46230951])

result[cam_list[2] + "-" + cam_list[3] + "_R"] = np.array([[ 0.57913545,  0.04026335, -0.81423645],
       [-0.14330689,  0.98825489, -0.05306032],
       [ 0.80253677,  0.14741481,  0.57810346]])
result[cam_list[2] + "-" + cam_list[3] + "_T"] = np.array([1640.69515123,   12.86900027,  960.24096852])

result[cam_list[2] + "-" + cam_list[1] + "_R"] = np.array([[ 0.66169192, -0.02274623,  0.74943073],
       [ 0.19528112,  0.97027054, -0.14296978],
       [-0.72389853,  0.24095162,  0.64646209]])
result[cam_list[2] + "-" + cam_list[1] + "_T"] = np.array([-1747.72631593,    42.87419725,   933.11764652])

result[cam_list[1] + "-" + cam_list[0] + "_R"] = np.array([[ 0.44199574,  0.02102015,  0.89677083],
       [-0.14921203,  0.98752016,  0.05039556],
       [-0.88451995, -0.15608362,  0.43961616]])
result[cam_list[1] + "-" + cam_list[0] + "_T"] = np.array([-1723.2720887 ,  -411.90040134,  1212.71975883])
#print(result)
with open('extrinsic.pkl','wb') as handle:
    pickle.dump(result, handle)